version: 2
jobs:
  build:
    working_directory: /temp
    docker:
      - image: microsoft/dotnet:sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet restore Items/Items.csproj
      - run: dotnet build Items/Items.csproj
      - run: dotnet restore Items.Tests/Items.Tests.csproj
      - run: dotnet test Items.Tests/Items.Tests.csproj