<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="QueryPage.aspx.cs" Inherits="ItemWeb.QueryPage" %>
<%@ Import Namespace="Items" %>
<%@ Import Namespace="ItemWeb" %>

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Model documentation</title>
		<link href="<% Response.Write(this.GetSiteURL()); %>/css/bootstrap.min.css" rel="stylesheet">
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
		<style>
			.big-number 
			{
				font-size: 3em;
			}
		</style>
	</head>
	<body>

		<nav class="navbar navbar-default">
			<div class="container-fluid">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand">Kitchen</a>
				</div>

				    <!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav navbar-right">
						<li><a href="../Index.aspx">Home</a></li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Queries<span class="caret"></span></a>
							<ul class="dropdown-menu">
								<% foreach (Item item in Global.Model.Items)
								{
									Response.Write(String.Format("<li><a href=\"{0}/Query/{1}\">{1}</a></li>", this.GetSiteURL(), item.Name));
								}
								%>
							</ul>
						</li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Queries<span class="caret"></span></a>
							<ul class="dropdown-menu">
								<% foreach (Item item in Global.Model.Items)
								{
									Response.Write(String.Format("<li><a href=\"{0}/Docs/Item/{1}\">{1}</a></li>", this.GetSiteURL(), item.Name));
								}
								%>
								<li role="separator" class="divider"></li>
								<% foreach (Category category in Global.Model.Categories)
								{
									Response.Write(String.Format("<li><a href=\"{0}/Docs/Category/{1}\">{1}</a></li>", this.GetSiteURL(), category.Name));
								}
								%>
								<li role="separator" class="divider"></li>
								<% foreach (Relationship relationship in Global.Model.Relationships)
								{
									Response.Write(String.Format("<li><a href=\"{0}/Docs/Relationship/{1}\">{1}</a></li>", this.GetSiteURL(), relationship.Name));
								}
								%>
							</ul>
						</li>
					</ul>
				</div>
			</div>
		</nav>

		<div class="container-fluid">
			<div class="row">
				<div class="col-sm-12">
					<h2>
						<% Response.Write(this.Thing.Name); %> <small><% Response.Write(this.ThingType); %></small>
					</h2>

					<% this.ProduceTable(); %>
				</div>
			</div>

			<div class="row">
				<div class="col-sm-6">
					<h2>Include Relationships</h2>
					<ul>
					<%
					foreach(Relationship relationship in this.Thing.GetReferenceRelationships(Global.Model).Where(relationship => relationship.Details.ContainsKey("SqlConstraint")))
					{
						Response.Write(String.Format(@"<li><a href=""{0}/Query/{1}/{2}"">{2}</a></li>", this.GetSiteURL(), this.Thing.Name, relationship.Name));
					}
					%>
					</ul>
				</div>
				<div class="col-sm-6">
					<h2>Executed Sql</h2>
					<pre><% Response.Write(this.executedSql); %></pre>
				</div>
			</div>

			<hr>

			<footer>
				<p>Generated by the Items project. Source available on <a href="https://github.com/bencoveney/Items">Github</a>. &copy; Ben Coveney 2015.</p>
			</footer>
		</div>

		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
		<script src="<% Response.Write(this.GetSiteURL()); %>/js/bootstrap.min.js"></script>

	</body>
</html>